name: CI JOBS
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: printing todays date 
        run: date 
      - name: printing calendar
        run: cal

  jobs:
    runs-on: macos-latest 
    needs: [job1]
    steps:
      - name: printing todays date 
        run: date 


